Feature/prml 213 improvements to get material names
rudderlabs/rudderstack-profiles-classifier pull request #176
Opened 2024-02-09 13:29 UTC by joker2411

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-02-12 06:37 UTC, shekhar-rudder commented on src/utils/utils.py
> +def date_add(reference_date: str, add_days: int, **kwargs) -> str:
Instead of adding a new flag `subtract` we can pass in a negative number in `add_days` argument

2024-02-12 06:37 UTC, shekhar-rudder commented on src/connectors/SnowflakeConnector.py
> +                    feature_seq_no = str(int(row.FEATURE_SEQ_NO))
What error are you seeing if you use `feature_seq_no = row.FEATURE_SEQ_NO` ?

2024-02-12 06:37 UTC, shekhar-rudder commented on src/connectors/Connector.py
> +            materialise_feature_data = utils.materialise_past_data(
Is it possible for both `feature_date` and `label_date` to be not None ? If yes, we can create an array of 2 elements - feature and label date. Then we range over the array elements to call `materialise_past_data`. This way, we can get rid of one of the function calls

2024-02-12 06:37 UTC, shekhar-rudder commented on src/connectors/Connector.py
> +        feature_label_snowpark_df,
We should generalize this argument. Base class should not have any knowledge of any of its child

2024-02-12 06:37 UTC, shekhar-rudder commented on src/connectors/SnowflakeConnector.py
> +                        material_table_prefix,
Why are we passing `material_table_prefix` as an argument ? The interested functions can directly access it via constants

2024-02-12 06:37 UTC, shekhar-rudder commented on src/connectors/SnowflakeConnector.py
> +                if (
The whole logic in this for loop is being duplicated in `RedshiftConnector`. We should move up the common logic to `Connector` class

2024-02-12 13:31 UTC, joker2411 commented on src/connectors/SnowflakeConnector.py
> +                    feature_seq_no = str(int(row.FEATURE_SEQ_NO))
after merging both the feature dataframe and label dataframe, it was converting sequence_number to float values. Handled it differently as suggested by @dpatchigolla in new commits.

2024-02-12 13:32 UTC, joker2411 commented on src/connectors/Connector.py
> +            materialise_feature_data = utils.materialise_past_data(
Yes. Both can be not None as well. Corrected it as per the comment.

2024-02-12 13:33 UTC, joker2411 commented on src/connectors/Connector.py
> +        feature_label_snowpark_df,
removed this argument in new commits.

2024-02-12 13:37 UTC, joker2411 commented on src/connectors/SnowflakeConnector.py
> +                        material_table_prefix,
yes. This is just for better readability, we pass all the values required to create material name in same order.

2024-02-12 13:48 UTC, joker2411 commented on src/connectors/SnowflakeConnector.py
> +                if (
Redshift and Snowflake both vary in accessing their columns and column values. Also, both are using their different sessions to validate the tables. I believe it's better to keep them separate.

2024-02-13 06:32 UTC, dpatchigolla requested changes

2024-02-13 06:32 UTC, dpatchigolla commented on src/connectors/Connector.py
> +        feature_material_seq_no: int,
Can you make typehint Optional[int] to indicate it can be None? same with label_material_seq_no

2024-02-13 06:32 UTC, dpatchigolla commented on src/connectors/RedshiftConnector.py
> +                    & (df["end_ts"].dt.date >= pd.to_datetime(start_time).date())
Can you add unit tests for this? Both in snowflake and redshift connectors? You can mock get_mateiral_registry_table to return a fixed dataframe, where you give predefined end_ts values and test that the logic works as expected?

2024-02-13 06:32 UTC, dpatchigolla commented on src/connectors/RedshiftConnector.py
> +                .assign(end_ts=lambda x: x["end_ts"].dt.date)  # convert to date
Why is this required?

2024-02-13 06:32 UTC, dpatchigolla commented on src/connectors/RedshiftConnector.py
> +            feature_label_df = feature_label_df.replace({np.nan: None})
You can add the `.replace({np.nan: None})` in prev line itself. Variable re-assigning should usually be avoided if possible. So, 
```
feature_label_df = pd.merge(
                feature_df, label_df, on="label_end_ts", how="outer"
            ).replace({np.nan: None})
```

2024-02-13 06:32 UTC, dpatchigolla commented on src/connectors/Connector.py
>          """This function will validate the input material query with seq number from historical material tables
_This function will validate the input material query with seq number from historical material tables_

This isn't really very helpful. Can you modify this to following? 

entity_var_table hash doesn't necessarily change if the underlying entity vars change. So we need to validate if the historic entity var tables were generated by the same model that is generating current entity var table. We do that by checking the input tables that generate entity var table, by replacing the current seq no with historic seq nos and verify those tables exist. This relies on the input sql queries sent by profiles which point to the current materialised tables.

2024-02-13 06:32 UTC, dpatchigolla commented on src/connectors/RedshiftConnector.py
> +                    break  # we might be taking more than 10 materials for training but this would consider all types of inputs.
>10 materials

Where is 10 coming from? Also I am not sure I understand this comment clearly. Can you try to rephrase it, and add it as a logger.debug instead of as a comment?

2024-02-13 06:32 UTC, dpatchigolla commented on src/connectors/SnowflakeConnector.py
> +                return True
How is it valid if table_name is None?

2024-02-13 06:32 UTC, dpatchigolla commented on src/connectors/SnowflakeConnector.py
> +                return True
This, and rest of comments in this is applicable for the RedshiftConnector too - and vice-versa - wherever they are relevant.

2024-02-13 10:54 UTC, joker2411 commented on src/connectors/RedshiftConnector.py
> +                .assign(end_ts=lambda x: x["end_ts"].dt.date)  # convert to date
removed.

2024-02-14 12:48 UTC, joker2411 commented on src/connectors/Connector.py
>                  if self.is_valid_table(session, feature_table_name_):
Yes, it shouldn't have any invalid tables because entries inside materials are only made after verifying if the table is valid or not.
Raised and assert.

2024-02-14 13:33 UTC, dpatchigolla approved these changes

2024-02-14 13:43 UTC, merged