Implementation for generating new material dates if the data is not s…
rudderlabs/rudderstack-profiles-classifier pull request #199
Opened 2024-02-27 07:42 UTC by cnu1439

…ufficient

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-03-04 09:13 UTC, dpatchigolla requested changes

2024-03-04 09:13 UTC, dpatchigolla commented on tests/unit/utils_tests.py
> +        result = utils.generate_new_training_dates(
Most of the logic is in actually calling the internal functions with the right params, so mocking those result without verifying the function calls seem incomplete - we are not checking the more complex part of the code. Can you add something like this (generated from chatgpt - needs modifications)

```       
 # Assert that date_add and dates_proximity_check were called with the correct parameters
        expected_date_add_calls = [
            call('2024-03-01', 30),
            call('2024-02-01', 30),
            call('2024-01-01', 30)
        ]
        mock_date_add.assert_has_calls(expected_date_add_calls)
        mock_dates_proximity_check.assert_called_once_with('2024-02-29', ['2024-02-01'], 30)
```

2024-03-04 09:13 UTC, dpatchigolla commented on tests/unit/utils_tests.py
> +        moc_date_add.side_effect = [
typo: `moc` -> `mock`

Also, I didn't understand these values. shouldn't the first value be date_add('2024-02-26', -5) = '2024-02-21'?

2024-03-04 09:13 UTC, dpatchigolla commented on tests/unit/RedshiftConnector.py
> +    def test_generate_new_materials_auto_strategy(
For this class - both the tests, can you also check whether the right function calls are getting made when you are mocking the results? example in utils test file

2024-03-04 16:27 UTC, cnu1439 commented on samples/application_project/models/profiles-ml.yaml
> +          - entity/user/user_var_table
I might have put this when it was failing to get past materials due to a bug.

2024-03-04 16:28 UTC, cnu1439 commented on samples/application_project/models/profiles-ml.yaml
> +          - entity/user/user_var_table
will remove it.

2024-03-04 17:02 UTC, cnu1439 commented on scripts/simulate_pb_run.py
> +    train_inputs = os.getenv("TRAIN_INPUTS")
yes, we need train inputs, past material validations are based on these inputs

2024-03-04 18:57 UTC, cnu1439 commented on src/connectors/Connector.py
> +        if met_data_requirement or strategy == "":
min data requirement is already met or there is no strategy to generate new materials, in either of the case we are going to return initial past materials

2024-03-04 18:59 UTC, cnu1439 commented on src/connectors/Connector.py
> +                max_feature_date = training_dates[0]
nope, this gives max date. which is more recent data. we wanted to generate more materials closer to recent date.

2024-03-04 19:00 UTC, cnu1439 commented on src/connectors/Connector.py
> +                f"new feature tables: {[m.feature_table_name for m in materials]}"
ok

2024-03-05 05:26 UTC, cnu1439 commented on src/connectors/CommonWarehouseConnector.py
> +            if len(result) != 0:
This need clarification, should be continue with initial meterials in case of error while generating new materials or should error out.

2024-03-05 05:30 UTC, cnu1439 commented on src/connectors/SnowflakeConnector.py
> +        print(f"start_ts: {start_time}, end_ts: {end_time}")
yes this is for debugging. will remove it.

2024-03-05 05:30 UTC, cnu1439 commented on src/connectors/SnowflakeConnector.py
> +                "Number training samples are not meeting the minimum requirement"
sure

2024-03-05 05:31 UTC, cnu1439 commented on src/trainers/MLTrainer.py
> +        new_materialisations_config = kwargs.get("new_materialisations_config", {})
no, will add those configuration.

2024-03-05 05:41 UTC, cnu1439 commented on src/utils/constants.py
> +MIN_NUM_OF_ROWS = 1000
We can manage with one variable.

2024-03-05 05:53 UTC, cnu1439 commented on src/utils/utils.py
> +def get_max_date_string(dates: list) -> str:
no actually, removing it.

2024-03-06 10:44 UTC, cnu1439 commented on src/utils/constants.py
> +MIN_NUM_OF_NEGATIVE_LABELS = 800
Done

2024-03-06 10:45 UTC, cnu1439 commented on tests/unit/utils_tests.py
> +        result = utils.generate_new_training_dates(
Done.

2024-03-06 10:48 UTC, cnu1439 commented on train.py
> +        train_table_pairs = get_material_names_partial(start_date=start_date)
putting new material generation inside try catch block. so we should be using same variable.

2024-03-06 10:50 UTC, cnu1439 commented on src/utils/utils.py
> +        logger.warning(
Removed this code.

2024-03-06 10:55 UTC, cnu1439 commented on src/utils/utils.py
> +        logger.warning(
we don't have to throw error here, can get away with this. this is being used for sorting dates, there we can ignore all empty dates.

2024-03-06 11:00 UTC, cnu1439 commented on src/utils/utils.py
> +    return str(date)
We could use something like this, but this will function become non-generic one.

2024-03-08 11:30 UTC, joker2411 commented on scripts/simulate_pb_run.py
> +
path not correct I think. Should be ```from src.predictions.rudderstack_predictions.utils.logger import logger```

2024-03-08 14:11 UTC, joker2411 commented on src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
> +            query_str = f"""SELECT COUNT(*) as count
If we can fetch the table using connector.get_table(), it would be great. As this would not be supported for BigQuery as it requires 'schema' as well for for running queries which is absent here.
We can apply filtering the dataframe received from it.

2024-03-08 14:14 UTC, joker2411 commented on src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
> +            query_str = f"""SELECT COUNT(*) as count
same error as above. This query would not be supported in bigquery.

2024-03-08 14:27 UTC, joker2411 commented on src/predictions/rudderstack_predictions/utils/utils.py
> +        datetime_obj = datetime.strptime(datetime_str, "%Y-%m-%d %H:%M:%S")
can you for the scenario when the given datetime_str is in "UTC" timezone.

2024-03-08 15:23 UTC, dpatchigolla commented on samples/application_project/models/profiles-ml.yaml
>                feature_data_min_date_diff": 14 # Minimum number of days in the difference between new generated material and existing materials
The `"` exists for this and the next few variables too.

2024-03-11 08:48 UTC, dpatchigolla approved these changes

2024-03-11 08:59 UTC, merged