working train for bigquery
rudderlabs/rudderstack-profiles-classifier pull request #205
Opened 2024-02-29 05:32 UTC by joker2411

Changes to be committed:
	modified:   scripts/simulate_pb_run.py
	modified:   src/connectors/BigQueryConnector.py
	modified:   src/connectors/CommonWarehouseConnector.py
	modified:   src/connectors/RedshiftConnector.py
	modified:   src/connectors/SnowflakeConnector.py
	modified:   src/ml_core/preprocess_and_train.py
	modified:   train.py

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-03-05 16:04 UTC, dpatchigolla requested changes

2024-03-05 16:04 UTC, dpatchigolla commented on src/connectors/wh/__init__.py
> +        creds["access_token"] = config.get("access_token")
Can you try something like this
```
# Define keys of interest for creds
creds_keys = ["access_token", "http_endpoint", "credentials"]

# Update creds dictionary for keys that exist in config
creds.update({key: config[key] for key in creds_keys if key in config})
```

2024-03-05 16:04 UTC, dpatchigolla commented on src/connectors/wh/__init__.py
> +        creds["access_token"] = config.get("access_token")
For db_config too

2024-03-05 16:18 UTC, shekhar-rudder commented on src/wht/rudderPB.py
> +            if "`" in mlower:  # BigQuery case table name
Can you add unit tests for the if-else scenario

2024-03-06 06:19 UTC, joker2411 commented on src/connectors/wh/__init__.py
> +        creds["access_token"] = config.get("access_token")
Well, I kept it like this because I wanted to mantain the same structure as in pywht/profiles_rudderstack, so that we can clearly figure out the differences in future.
But if you suggest, we can change it in classifier repo.

2024-03-06 06:51 UTC, joker2411 commented on src/utils/utils.py
> +    try:
yes. correcting.

2024-03-06 06:55 UTC, joker2411 commented on src/wht/rudderPB.py
> +            if "`" in mlower:  # BigQuery case table name
Sure. Adding.

2024-03-06 07:00 UTC, joker2411 commented on train.py
> +        connector.make_local_dir()
yes. Last time, I have missed seeing just the line above this. Since that contains ```connector.cleanup(delete_local_data=True)```, it would delete the local folder right after creating it and would throw error later.

2024-03-06 07:22 UTC, joker2411 commented on src/connectors/wh/bigquery_base_connector.py
> +                name=table_name.replace("`", ""),
No, we don't. We usually provides string inputs to the function. Though this case is for the considtion if table_name has is in format ```schema.table```. 
This is also taken from pywht/profiles_rudderstack and wouldn't harm our case as well.

2024-03-06 07:25 UTC, joker2411 commented on tests/unit/utils_tests.py
> +            f"expected string or bytes-like object",
yes. That's because of re.search(). Removing this test and adding few others instead.

2024-03-06 07:46 UTC, joker2411 commented on src/connectors/CommonWarehouseConnector.py
> +                table[field].dtype != "int64"
planning to configure ```get_stringtype_feature()``` in task [PRML-427](feature/prml-427-refactor-the-functions-that-infer-the-datatypes-in-the) to fetch it from schema and would change this as well in same task.

2024-03-06 07:48 UTC, joker2411 commented on src/connectors/RedshiftConnector.py
> +        non_stringtype_features = []
both ```stringtype_features``` and ```non_stringtype_features``` are checking pandas DataFrame but will change it so that they are fetched from schema in [PRML-427](feature/prml-427-refactor-the-functions-that-infer-the-datatypes-in-the). 

Didn't want to break the code for redshift till then, that's why haven't made any changes yet.

2024-03-06 07:48 UTC, joker2411 commented on src/connectors/RedshiftConnector.py
> +    def get_stringtype_features(
same as above.

2024-03-06 07:49 UTC, joker2411 commented on src/connectors/BigQueryConnector.py
> +            if all(isinstance(value, list) for value in table_df[column])
corrected.

2024-03-06 11:34 UTC, closed without merging