pycaret update
rudderlabs/rudderstack-profiles-classifier pull request #210
Opened 2024-03-06 20:49 UTC by subham-71

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-03-26 11:37 UTC, dpatchigolla requested changes

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
> +        preds = preds.withColumn("columnindex", F.row_number().over(w))
Why did you require a window function? Earlier it wasn't needed right? Order of rows in a distributed dataframe is not deterministic, so I am not sure how  joining on monotonically increasing id is working here. Why can't you use the method like earlier? `predictions_df.select(..., .., prediction_udf(*input))`

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +        # train_results_json = train_procedure(session,filtered_feature_table,train_config,feature_table_column_types)
Can you remove the comment

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +    def prepare_data_(
Rename to `_prepare_data` -> The `_` should be at the start of the name for internal functions

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +        categorical_columns: List[str],
Are categorical_columns and numerical_columns being used?

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +        model_setup,
Can you add typehints as `Callable`? You can import from Typing. This indicates these are functions.
You can also add `pycaret_` prefix to these three variables that help understand where these are coming from

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +            train_data,
Do we need both the (train_x, train_y), and train_data? We can generate `train_data` from the other two right?

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +            fold=5,
Can you move this fold and fold_strategy to `preprocess_config`

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +            y_true = y.to_numpy()
you can remove label_column from params if its not used anymore

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> -            y_true = y[label_column.upper()]
Same as classifier. remove the param if not req.

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +            y_pred,
Is this binary or prob scores? Looks like earlier it was binary but now its scores?

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +
This function seems to fit better in ClassificationTrainer (and the regression equivalent in RegressionTrainer). wdyt?

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +        target=label_column.upper(),
PyCaret doesn't need val dataset. Once you work on that ticket, you should make train = train + val, and keep test split as is.

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +    for col in numeric_columns:
Why is this different here? And the transformation si inconsistent with the comment. Also you can remove the comments everywhere in your pr, unless it's explaining a very complex logic.

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +    y_true = pd.Series(y_true)
Can you add typehints to the function? Was the expected input a numpy array?

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +    model, train_x, numeric_columns, categorical_columns, figure_file, top_k_features=5
Remove unused params

2024-03-26 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +        session (object): The session object used for writing the feature importance values and saving the chart image.
Remove Args docstring

2024-03-26 11:57 UTC, subham-71 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
> +            def end_partition(self, df):
end_partition is the function we have to update in case of an udtf. Link :  https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-tabular-vectorized

2024-03-26 12:01 UTC, subham-71 commented on src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
> +        preds = preds.withColumn("columnindex", F.row_number().over(w))
I had to use the  id to join the dfs. Tried other ways but they didn't work if the col name wasn't present earlier in one of the dfs.

2024-04-10 12:18 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/train.py
>              numeric_columns = feature_table_column_types["numeric"]
Looks like numeric_columns and categorical_columns are not being used anymore. Can you remove these then?

2024-04-10 12:19 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/train.py
> +            model_file = model_file + ".pkl"
We were earlier using joblib. Any reason why you made it pkl?

2024-04-10 12:28 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
>          write_mode="overwrite",
Why are these params removed?

2024-04-10 12:30 UTC, subham-71 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
>          write_mode="overwrite",
I modified the udf function into a udtf. Also prob_th isn't being used anymore.

2024-04-10 12:36 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
> +        if prediction_task == "classification":
Can you add a comment here
`# ToDo: To move them to trainer class`

We can pick these later.

2024-04-10 12:39 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
> +        pred_output_df_columns = {
This dict seems to be present in a few different places. Can you move this to constants, with `classification` and `regression` as keys and the `label`, `score` part as values? so the code here would be:

`pred_output_df_columns = constants.PRED_OUTPUT_DF_COLUMNS[prediction_task]`

2024-04-16 17:04 UTC, joker2411 commented on src/predictions/rudderstack_predictions/train.py
>                  feature_df,
@dpatchigolla
Since, we are no longer using `numeric_columns` and `categorical_column` to train the model, we can remove the `feature_table_column_types` argument passed to training procedure.

2024-04-16 17:07 UTC, joker2411 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +        feature_df, train_config, model_file
@dpatchigolla
Similar to snowflake, we can remove `numeric_columns`, `categorical_columns` and `feature_table_column_types` argument to this function as well.
In fact if this is not being used anywhere, then I believe there is no point in even calculating it. 
I think we can skip that completely. What do you think?

2024-04-16 17:11 UTC, joker2411 commented on src/predictions/rudderstack_predictions/predict.py
> +from .trainers.ClassificationTrainer import ClassificationTrainer
I guess we can remove `ClassificationTrainer` and `RegressionTrainer` imports after ConnectorFactory import as this is not being used anywhere.

2024-04-16 17:19 UTC, joker2411 commented on src/predictions/rudderstack_predictions/utils/constants.py
> +    "pycaret",
Shouldn't we pin-point the pycaret version on training-procedure to stay away from sudden errors.

2024-04-16 17:30 UTC, joker2411 commented on src/predictions/rudderstack_predictions/connectors/Connector.py
> +                if key not in lowercase_list(ignore_features)
we'll have to check for lowercase key: 
```if key.lower() not in lowercase_list(ignore_features)```

2024-04-16 17:54 UTC, joker2411 commented on src/predictions/rudderstack_predictions/utils/utils.py
> +        shap.plots.beeswarm(shap_values, max_display=20, show=False)
use argument `top_k_features` instead of 20.

2024-04-16 18:00 UTC, joker2411 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +        feature_df, train_config, model_file
Checked. It is being used in `preprocess_and_predict.py`. Thus, we can't remove it completely but ca remove it as argument from here.

2024-04-16 18:13 UTC, joker2411 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    transformed_arraytype_cols, feature_table = connector.transform_arraytype_features(
@dpatchigolla
Not a change here but for future reference.
Since `transform_arraytype_features()` would change the column_names and create new features. So, while doing numeric encoding, instead of filling 0 as default in those columns, if we can use NA/None, then we can calculate `high_cardinal_features` after the arraytype transformation and include sparse features in ignore_features.

Steps would be in order-> 
1. transform_arraytype_features
2. fetch_high_cardinal_features
3. calculate_ignore_features

This can be useful in case if actual data has arraytype columns and which after transforming, are generating a lot of features resulting in a larger but sparse matrix.(Not any changes needed here)

2024-04-17 00:44 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/constants.py
> +    "pycaret",
There's a single version, 3.0.3 on snowpark while we have tested 3.3.0 too. May be good idea to make it `pycaret<=3.3.0`

2024-04-17 02:31 UTC, dpatchigolla requested changes
Added a few comments - some clarifications and changes requested.

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
> +                    types.append(T.StringType())
Why do you need an if-else statement here? Is the else a fail-safe?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
> +                    )
```if col in input_column_types_map["numeric"]:
                    types.append(
                        self.data_type_mapping["numeric"][
                            input_column_types_map["numeric"][col]
                        ]
                    )
```
This whole block is repeated above too, for categorical. Can you abstract that to a sub-function within this function and call that with the categorical/numeric params?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
> +        pycaret_score_column_name = pred_output_df_columns["score"].upper()
@joker2411 can you check this block once?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    transformed_arraytype_cols, feature_table = connector.transform_arraytype_features(
@joker2411 Can you create a ticket for this?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
> +    load_model as classification_load_model,
these libraries seem to be not used in the file.

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
> +    print("Columns: ", predict_data.columns)
Remove print statement.

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
> +            is_permanent=False,
Why is `max_batch_size` removed?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
>          write_mode="overwrite",
Yes. s3 params should not be removed. Is there a reason why they were removed?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +        preprocess_config = {
Where is this being used?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +        # Initialize PyCaret setup for the model with train and test data
Why are you writing the data to the disc?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +        train_x_transformed = pycaret_get_config("X_train_transformed")
What is `train_x_transformed`? How is it being used downstream?

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +    def train_model_(
Add `_` as prefix, not suffix.

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/ClassificationTrainer.py
> +        test_metrics["users"] = int(1 / fold_param * len(X_train))
This is val_metrics user count. Test metrics user count would be from model config, which was being used in split_train_test.

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/RegressionTrainer.py
> +        key_mapping = {
Can you add these to the init? So constants are defined at start of classes? This should be uniform across the project. Please make sure you are not adding constants in between functions. They should all be at the top of that respective class.

2024-04-17 02:31 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/RegressionTrainer.py
> +        test_metrics["users"] = int(1 / fold_param * len(X_train))
Same comment as in ClassificationTrainer

2024-04-17 04:32 UTC, joker2411 commented on src/predictions/rudderstack_predictions/connectors/Connector.py
> +    ) -> Dict:
`get_timestamp_columns()` hasn't been edited. So, there was no option to add the comments there.

2024-04-17 04:40 UTC, joker2411 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    transformed_arraytype_cols, feature_table = connector.transform_arraytype_features(
Ticket [link](https://linear.app/rudderstack/issue/PRML-515/fetch-high-cardinal-features-after-transform-arraytype-features)

2024-04-17 09:51 UTC, joker2411 commented on src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
> +        pycaret_score_column_name = pred_output_df_columns["score"].upper()
`        prediction_df = input.select(
            prediction_udf(*input.columns).over(partition_by=[input.columns[0]])
        )
`
Above piece of code is failing because of arguments types not matching. Facing this on Snowflake.

2024-04-17 09:56 UTC, joker2411 commented on src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
> +        pycaret_score_column_name = pred_output_df_columns["score"].upper()
I believe arguments types while passing to UDTF are in Format of `FLOAT, NUMBER(38,0) etc` but our calculated types are in format `DoubleType(), LongType() etc`. That can be the possible cause of mismatch.

2024-04-17 11:37 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/ClassificationTrainer.py
> +                "greater_is_better": False,
Doesn't this `False` mean the model tries to minimise roc_auc_score?

2024-04-17 11:40 UTC, dpatchigolla requested changes

2024-04-17 11:40 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/trainers/ClassificationTrainer.py
> +                "greater_is_better": False,
Also, is this supposed to be used for optimisation? We want to maximise on f1-score (is that possible out of the box? if not lets do on pr-auc), but not on roc-auc; We need roc-auc only for optimisation.

2024-04-17 20:43 UTC, subham-71 commented on samples/predictions_dev_project/models/profiles.yaml
> +            name: is_churned_10_days
To test the project for classification.

2024-04-17 21:04 UTC, subham-71 commented on src/predictions/rudderstack_predictions/utils/utils.py
> +        input_column_types["numeric"][col] = T.DecimalType()
We can change this to `None`,  this is to maintain the map structure. Downstream in train, we just need the map keys to save them in train_output.json.

The map structure is utilized during the predict script.

2024-04-17 21:06 UTC, subham-71 commented on src/predictions/rudderstack_predictions/utils/utils.py
> +        df[col] = df[col].fillna(0)
We can remove the transform_null function , since we no longer use it. SimpleIputer can be passed as preprocess config to pycaret

2024-04-17 21:25 UTC, subham-71 commented on src/predictions/rudderstack_predictions/utils/utils.py
> +
Yes, We can have them inside the trainers and remove the TrainerUtils Class

2024-04-17 21:29 UTC, subham-71 commented on src/predictions/rudderstack_predictions/utils/constants.py
> +import shap
Can we rename the file from `constants` to something flexible as in `globals`? Since the map fits well in this file.

2024-04-17 21:29 UTC, subham-71 commented on src/predictions/rudderstack_predictions/utils/constants.py
> +    "RidgeClassifier": shap.LinearExplainer,
Sure

2024-04-17 22:17 UTC, subham-71 commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +        train_x_transformed = pycaret_get_config("X_train_transformed")
It is the preprocessed dataframe from the pycaret pipeline, that is used for training. It is used to generate the shap values for feature importance.

2024-04-17 22:33 UTC, subham-71 commented on src/predictions/rudderstack_predictions/trainers/ClassificationTrainer.py
> +                "greater_is_better": False,
We can have a parameter , `metric_to_optimize` which will be used to compare the models.

2024-04-17 22:36 UTC, subham-71 commented on src/predictions/rudderstack_predictions/trainers/MLTrainer.py
> +        # Initialize PyCaret setup for the model with train and test data
Sorry, Couldn't understand it. This doesn't save the data  to the disc.

2024-04-17 22:53 UTC, subham-71 commented on src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
> +        input_column_types_map,
It is not being used currently since we directly append `str` or `float` for type hints in this case. In future, we can utilize this when we have to handle specific datatypes on the warehouses.

2024-04-17 23:50 UTC, subham-71 commented on src/predictions/rudderstack_predictions/utils/utils.py
>      train_size: float,
We are calling these functions using self._getPB(), so in case of MockPB , these should be available too.

2024-04-17 23:52 UTC, subham-71 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
> +            is_permanent=False,
It fails during the integration test saying no parameter found for pandas udtf, but works locally.

2024-04-22 03:25 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/constants.py
> +import shap
Lets take it up later. for now, move shap to the top of the file. Imports in middle of the file isn't right.

2024-05-23 05:45 UTC, dpatchigolla requested changes

2024-05-23 05:45 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/Connector.py
> +    def get_booleantype_columns(
Why do we have this method defined twice?

2024-06-12 07:22 UTC, dpatchigolla approved these changes

2024-06-12 07:22 UTC, merged