restructuring numeric and categorical feature fn.
rudderlabs/rudderstack-profiles-classifier pull request #219
Opened 2024-03-11 08:06 UTC by joker2411

Changes to be committed:
	modified:   src/predictions/rudderstack_predictions/connectors/BigQueryConnector.py
	modified:   src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
	modified:   src/predictions/rudderstack_predictions/connectors/RedshiftConnector.py

## Description of the change

> Restructuring get_datatype_fun()

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-03-18 11:57 UTC, shekhar-rudder commented on src/predictions/rudderstack_predictions/wht/pythonWHT.py
> +    def get_input_column_types(
Why have we added this method in pythonWHT ?

2024-03-18 11:57 UTC, shekhar-rudder commented on src/predictions/rudderstack_predictions/wht/pythonWHT.py
> +    def latest_existing_entity_var_table_from_registry(
If we are adding this method, then we should get rid of `get_latest_entity_var_table`

2024-03-18 15:26 UTC, joker2411 commented on src/predictions/rudderstack_predictions/wht/pythonWHT.py
> +    def get_input_column_types(
Moved to Connector.py

2024-03-18 15:27 UTC, joker2411 commented on src/predictions/rudderstack_predictions/wht/pythonWHT.py
> +    def latest_existing_entity_var_table_from_registry(
both the functions are necessary. as this fn. takes _model_hash_ and _feature_model_name_ coming from ```get_latest_entity_var_table ``` as input and fetching seq_no.

2024-03-18 15:35 UTC, shekhar-rudder commented on src/predictions/rudderstack_predictions/wht/pythonWHT.py
> +    def latest_existing_entity_var_table_from_registry(
> this fn. takes model_hash and feature_model_name coming from get_latest_entity_var_table

The implementation of `get_latest_entity_var_table` function can be inlined here. And this function can return all the required details

2024-03-19 01:54 UTC, dpatchigolla requested changes

2024-03-19 01:54 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    train_results_json["column_names"] = {}
The train_results_json structure looks a bit complex. Can you add a check in integration tests around the format of how this dict is supposed to look?

2024-03-19 01:54 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +):
Can you modify the docstring to follows:
`Combines Feature table and Label table pairs, while converting all timestamp cols to numeric to create a single table with user features and label`
You can get rid of the `Args:` and `Returns:` section.

2024-03-19 01:54 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/wht/pythonWHT.py
> +        latest_entity_var_table_name = self.compute_material_name(
This is duplicating the same info from the rest of the params, except for the seq_no. Why not send seq_no too and stitch the name in train function?

2024-03-19 01:54 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/RedshiftConnector.py
> +    def fetch_schema(
Rename suggestion:
fetch_schema -> fetch_table_metadata

2024-03-19 01:54 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/RedshiftConnector.py
> +        numeric_data_types = (
Can you define the constants (this, timestamp_datatypes, and string_data_types) as class level constants? ex: how we defined `evalution_metrics_map` in ClassificationTrainer

2024-03-19 01:54 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
> +        schemaField = self.fetch_schema(session, table_name)
This function is getting called multiple times - once per datatype. This is a network call, hitting the warehouse each time. Can you think of a way to make a single network call and use the data for all columns? You can create a class level property and use it. 
Ignore if this is making things complex.

2024-03-19 01:54 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/wht/pythonWHT.py
> +        seq_no = self.connector.get_latest_seq_no_from_registry(
We usually don't need latest seq_no. We need the seq_no of current run, which is different. Think of scenario where we have two projects running in same schema at same time. 
Seq_no of current run can be extracted from the sql queries in input params of train.

2024-03-19 01:54 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
> +    def get_latest_seq_no_from_registry(
Check the comment in pythonWHT file. We may not need this function.

2024-03-19 10:41 UTC, joker2411 commented on src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
> +        schemaField = self.fetch_schema(session, table_name)
created another issue for [that](https://linear.app/rudderstack/issue/PRO-2220/refactor-fetch-table-metadata-so-that-it-is-hitting-warehouse-only). Will take it up there after BigQuery tasks.

2024-03-21 01:19 UTC, dpatchigolla approved these changes

2024-03-21 01:19 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +    schema_table_name = select_query.split(" ")[-1]
Why not just `select_query.split("_")[-1]`? Does it not work for any warehouse? 
We don't need to separate the table name, schema name and all.

2024-03-21 03:55 UTC, joker2411 commented on src/predictions/rudderstack_predictions/utils/utils.py
> +    schema_table_name = select_query.split(" ")[-1]
I am also considering for scenarios related to BigQuery because in that case, select query provided as input in train are as following:
```select * from `schema_name`.`table_name`,```

2024-03-21 03:56 UTC, merged