added support for arraytype features
rudderlabs/rudderstack-profiles-classifier pull request #234
Opened 2024-03-24 19:37 UTC by subham-71

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-03-25 05:21 UTC, dpatchigolla requested changes

2024-03-25 05:21 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +def transform_arraytype_features(feature_table, arraytype_features):
Can you add typehints?

2024-03-25 05:21 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +            *group_by_cols, F.explode(array_col_name).alias("ARRAY_VALUE")
This looks like snowpark? So currently it works only on Snowflake? It should be behind snowflakeconnector so a connector.transform_array_type_features() works on all warehouses. 
What's the plan with other warehouses?

2024-03-25 05:21 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +def transform_arraytype_features(feature_table, arraytype_features):
Please add unit test to test the functionality of it. Should cover atleast following:
1. A table with multiple array_type columns, having non empty arrays + empty arrays mixed in the results
2. A table with array type column with all empty arrays, no valid results
3. A table with zero array_type columns

2024-03-25 05:21 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +            row["ARRAY_VALUE"].strip('"')
Why is strip required?

2024-03-25 05:21 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/utils/utils.py
> +        exploded_df = feature_table.select(
The logic inside this for loop is a bit complex. Can you extract that out as a separate function (and write unit-tests for that too)

2024-03-25 05:23 UTC, subham-71 commented on src/predictions/rudderstack_predictions/utils/utils.py
> +            row["ARRAY_VALUE"].strip('"')
It is required to access the columns from snowpark tables.

2024-03-25 05:24 UTC, subham-71 commented on src/predictions/rudderstack_predictions/utils/utils.py
> +            *group_by_cols, F.explode(array_col_name).alias("ARRAY_VALUE")
Will move the logic from utils to connector and handle for other warehouses.

2024-03-26 07:11 UTC, dpatchigolla requested changes
Some minor comments. Also can you take a go ahead from @joker2411 ?

2024-03-26 07:11 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
> +    ) -> Union[list, pd.DataFrame]:
Is this a List[str]? Can you modify that? In return type too. In SnowflakeConnector as well.

2024-03-26 07:11 UTC, dpatchigolla commented on src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
> +        write_mode = kwargs.get("write_mode", "overwrite")
Why is this required? Changing defaults should be done carefully. Why not add 'overwrite' as a parameter instead of modifying the default itself?

2024-03-26 07:40 UTC, joker2411 commented on src/predictions/rudderstack_predictions/utils/utils.py
>      feature_table, input_column_types, config_ignore_features, high_cardinal_features
if ```input_column_types``` are not being used, we can remove this from arguments.

2024-03-26 07:51 UTC, joker2411 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    transformed_arraytype_cols, feature_table = connector.transform_arraytype_features(
We can move this function above ```connector.get_high_cardinal_features()``` function call.

2024-03-26 07:53 UTC, joker2411 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    for col in transformed_arraytype_cols:
make these changes inside ```utils.get_feature_table_column_types()``` to calculate feature_table_column_types.

2024-03-26 08:01 UTC, joker2411 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    for col in transformed_arraytype_cols:
Also, I believe this is as per considering the assumption that values inside the arrays are integer/float type. What if we have array of strings ?

2024-03-26 08:11 UTC, subham-71 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    for col in transformed_arraytype_cols:
We can't have strings since it is a count of the unqiue occurences.

2024-03-26 08:16 UTC, joker2411 commented on src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> +    for col in transformed_arraytype_cols:
yes. realised it while going through the PR. Deleted comment.

2024-03-26 09:36 UTC, merged