Changed the sql query to add features
rudderlabs/rudderstack-profiles-classifier pull request #380
Opened 2024-07-22 08:38 UTC by RuLeKiLLeR

## Description of the change

Changed the sql query to add features

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-07-22 10:02 UTC, dpatchigolla requested changes

2024-07-22 10:02 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +                    if value_flag
Why is there a value_flag check for cost_per_conv? Shoudln't it be only for return on ad spend? Looks like the else condition has the same string again? What's the purpose of the if-else block here

2024-07-22 10:02 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +                    f"""coalesce({conversion_name}_first_touch_conversion_value, 0) / nullif(coalesce(cost, 0), 0) AS {conversion_name}_first_touch_roas,
Same as above. This should be cost/value, not value/cost;

Also both should handle scenario of  denominator having 0. If denominator is zero, it should just default to zero.

2024-07-23 05:28 UTC, RuLeKiLLeR commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +                    if value_flag
The idea was to wait for your direction on where to use the value flag that is why added the same string in both if-else. Now you have provided me with more context hence I have formatted it properly now.

2024-07-23 05:37 UTC, dpatchigolla approved these changes

2024-07-23 06:37 UTC, merged