Added the functionality of conversion_window in conversion_vars
rudderlabs/rudderstack-profiles-classifier pull request #407
Opened 2024-08-07 16:55 UTC by RuLeKiLLeR

## Description of the change

Added the functionality of conversion_window in conversion_vars

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-08-08 12:40 UTC, dpatchigolla requested changes

2024-08-08 12:40 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +                conversion_var["conversion_window"] = "90d"
_In the build spec schema, add a new key conversion_window for each conversion in conversions_var. This should be optional._ 

_~If it's not provided by the user, it should get a default value of 90d.~_

This requirement got changed in the beginning itself. Default should be No conversion window, in which case, there should be no filter on the datediff between first/last touch date and conversion date

2024-08-08 12:40 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +            match = re.match(r"(\d+)([mhd])", conversion_window)
Is there a reason you modified the regex from the ticket `r'^\d+[mhd]$'`?That would match the word exactly while this would allow text before and after the intended duration (ex: `30d days` would pass this regex)

![image](https://github.com/user-attachments/assets/f1e4c6ad-9204-4749-9bdf-822574106803)

2024-08-08 12:40 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +                conversion_window_days = quantity  # 1 day = 1440 minutes
`conversion_window_days` can be outside the if-else conditions as it's the same in all conditions. You can also keep it `n_conversion_window` to make it applicable to hours and minutes too.

2024-08-08 12:40 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +                conversion_flag = "hour"
Can you rename `conversion_flag` to `conversion_granularity`

2024-08-08 16:01 UTC, RuLeKiLLeR commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +                conversion_var["conversion_window"] = "90d"
So should i remove this here, because then I will have to make changes in the below script as well

2024-08-08 18:59 UTC, RuLeKiLLeR commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +                conversion_var["conversion_window"] = "90d"
Removed it

2024-08-09 05:53 UTC, RuLeKiLLeR commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +            match = re.match(r"(\d+)([mhd])", conversion_window)
Changed it back. I was using the different regex to divide the string into parts

2024-08-09 09:19 UTC, dpatchigolla requested changes

2024-08-09 09:19 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> +            + (
There's too much of duplication in this blocks. 
Can you manage the if-else conditions outside and create those strings, then add them here? 
Something like this (DON'T ADD IT DIRECTLY - TEST IT AND MODIFY IF REQUIRED):

```
def _generate_date_case(field, conversion_flag):
    if conversion_flag:
        return f"""CASE 
            WHEN DATEDIFF({conversion_granularity}, {field}_timestamp, converted_date) <= {conversion_window} THEN DATE({field}_timestamp) 
            ELSE NULL 
        END AS {field}_date"""
    else:
        return f"DATE({field}_timestamp) AS {field}_date"

def _generate_value_case(field, conversion_flag, value_flag):
    if conversion_flag and value_flag:
        return f"""CASE 
            WHEN DATEDIFF({conversion_granularity}, {field}_timestamp, converted_date) <= {conversion_window} THEN {field}_conversion_value 
            ELSE NULL 
        END AS {field}_conversion_value"""
    elif value_flag:
        return f"{field}_conversion_value AS {field}_conversion_value"
    else:
        return ""

def generate_query_part():
    query_parts = []
    
    for attribution_type in ['first_touch', 'last_touch']:
        query_parts.append(_generate_date_case(attribution_type, conversion_flag))
        query_parts.append(f"{attribution_type}_{campaign_id_column_name}")
        query_parts.append(_generate_value_case(attribution_type, conversion_flag, value_flag))
    
    return ",\n".join(filter(None, query_parts))

query_part = generate_query_part()

```

2024-08-09 12:51 UTC, merged