integrating sql_model as input
rudderlabs/rudderstack-profiles-classifier pull request #436
Opened 2024-08-29 09:54 UTC by joker2411

## Description of the change

> Ticket [link](https://linear.app/rudderstack/issue/PRML-879/change-fetching-past-data-to-include-sql-model-inputs-as-well).

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-09-03 10:37 UTC, dpatchigolla requested changes

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/train.py
> +    tables_set_to_drop = set()
Rename `tables_set_to_drop` -> `past_joined_input_tables_set`

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/train.py
> +    tables_set_to_drop = set()
Try to name variables and functions with what they are instead of why they are written - the Why gets clear where it's being used.

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/utils/utils.py
> +def replace_seq_no_in_query(query: str, seq_no: int) -> str:
Can you write a unittest for this?

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/connectors/Connector.py
> +    def join_input_tables(
Can you write unittests for this and test the generated query?

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/wht/pythonWHT.py
> +        for input in inputs:
This modifies the global values of inputs dictionary. This is risky, may not have affect right away but the `inputs` variable changes globally with this. Can you modify it so that the dict contents doesn't change? 
In general, modifying mutable objects within a function is dangerous. We shouldn't do it unless it's by design

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/wht/pythonWHT.py
> +        for input in inputs:
How about doing this instead - don't even write this function:
1. Create a new function called `get_past_inputs(current_inputs: Inputs, past_seq_no: int) -> Inputs:` -> This takes current inputs, and prepares past inputs dict. A new dict, with the relevant seq numbers. 
2. When this current function is being called below, we instead call that function `get_past_inputs`, to get the `past_inputs` list. We also get the past_join_table_name there itself
3. Make a call to join_input_tables directly there itself.

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/connectors/Connector.py
> +        for input in inputs:
`input` is  a function in python. Can you add a `_` suffix?

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/connectors/Connector.py
> +    def join_input_tables(
This function actually looks a bit complex. Can you split this into a few sub-functions?

```
def join_input_tables(....):
     tables = self. _get_table_info(...)
     join_query = self._construct_join_query(...)
     self.write_joined_input_table(query, temp_joined_input_table_name)
```

2024-09-03 10:37 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/connectors/Connector.py
> +    def join_input_tables(
Writing unit tests for individual components too will be easier that way

2024-09-03 13:34 UTC, joker2411 commented on src/predictions/profiles_mlcorelib/connectors/Connector.py
> +            ind_input_columns = set(self.run_query(query)[0]._fields)
made a commit to correct it. Can you recheck this.

2024-09-04 06:41 UTC, joker2411 commented on src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py
> +        # TODO: Implement this function once we completely move to pynative model
If we migrate it right now, it would throw the error for Torpedo. Creating another ticket for this and will take it as soon as they're migrated to pyNative. Ticket link.

2024-09-04 06:43 UTC, joker2411 commented on samples/py_native/pb_project.yaml
> +    url: https://github.com/rudderlabs/profiles-features-integration-test/tree/feature/prml-839-modify-integration-tests-to-support-sql-models
migrated to main branch because previous tags were outdated.

2024-09-04 13:13 UTC, dpatchigolla requested changes

2024-09-04 13:13 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/wht/pythonWHT.py
> +            past_input = input.copy()
<img width="364" alt="image" src="https://github.com/user-attachments/assets/00223354-2edd-4141-baa0-fdb285456cb4">

copy only creates a shallow copy, and the values actually changes the source dict. see example. 

can you use copy.deepcopy()

2024-09-04 13:13 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/wht/pythonWHT.py
> +            past_input = input.copy()
Also, `input` -> `input_`

2024-09-05 05:10 UTC, dpatchigolla approved these changes

2024-09-05 07:02 UTC, merged