adding query for highest count of other ids
rudderlabs/rudderstack-profiles-classifier pull request #488
Opened 2024-10-18 04:11 UTC by joker2411

## Description of the change

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-955/1-add-drews-feedback-to-id-stitcher-analysis-tool).

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-10-18 10:46 UTC, dpatchigolla requested changes

2024-10-18 10:46 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py
> +        SELECT other_id_type, {main_id_key}, max_count
Why not just have max(count) in prev query itself?

2024-10-18 10:46 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py
> +        SELECT other_id_type, {main_id_key}, max_count
We don't need to get the main_id with highest count here.

2024-10-18 10:46 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py
> +                "Following id types are defined in id stitcher graph before id-stitching to come from same table, but we do not have any direct edges between them in the data (indirect edges can exis
Lets reword to

`Following id types are defined in id stitcher model inputs to come from same table, but we never see them together before id-stitching (they may be linked later by the stitching through other ids though).`

2024-10-20 13:06 UTC, joker2411 commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py
> +        SELECT other_id_type, {main_id_key}, max_count
ok.

2024-10-21 01:42 UTC, dpatchigolla approved these changes

2024-10-21 03:07 UTC, merged