Feature/prml 1011 pynative model feedback
rudderlabs/rudderstack-profiles-classifier pull request #510
Opened 2024-11-13 10:58 UTC by joker2411

## Description of the change

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1011/pynative-model-feedback).

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2024-11-13 11:43 UTC, dpatchigolla requested changes

2024-11-13 11:43 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
> +            match user_input.lower():
This doesn't work in python 3.9 afaik. Can you check? Ideally we should try to support 3.8 and above unless strong reason

2024-11-13 11:43 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
> +                "\n\nDo you want to run the audit again? (yes/no)"
> Do you want to run the audit again? (yes/no)

Rename to:

> Do you want to run the audit on a different id_stitcher model? (yes/no)

2024-11-13 11:43 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py
> +import webbrowser
Does this need to be in setup.py?

2024-11-13 11:43 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py
> +            webbrowser.open_new_tab("file://" + file_path)
This doesn't work if file_path contains `#` (our slack channel name as an entity has this) or any such special characters. We need to encode the file_path
Something like this should suffice:
```
import webbrowser
from urllib.request import pathname2url
from urllib.parse import urljoin

file_url = urljoin('file:', pathname2url(file_path))
webbrowser.open_new_tab(file_url)
```

2024-11-13 11:43 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/llm_report.py
> +class Colors:
This doens't work for windows. can you do this:
```
from colorama import init, Fore, Style

# Initialize colorama
init()

class Colors:
    BLUE = Fore.BLUE
    YELLOW = Fore.YELLOW
    GREEN = Fore.GREEN
    ENDC = Style.RESET_ALL
    ```
    
    Also, colorama should be added to setup.py

2024-11-13 12:18 UTC, joker2411 commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py
> +import webbrowser
`webbrowser` is part of the python standard library.

2024-11-13 12:31 UTC, joker2411 commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
> +            match user_input.lower():
I used it mainly because of standardizing it thoughout the code.

As the same way of reading inputs through reader object is being used in the whole code everywhere.

2024-11-13 12:33 UTC, joker2411 commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
> +            match user_input.lower():
In case of future changes, we can directly make changes in reader `get_input()` directly.

2024-11-14 05:28 UTC, dpatchigolla commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
> +            match user_input.lower():
Where else do we use match case in the code?

2024-11-15 04:45 UTC, joker2411 commented on src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
> +            match user_input.lower():
misunderstood. Corrected the code.

2024-11-15 05:09 UTC, merged